blueprint:
  name: "Zigbee2MQTT - MOES Smart Knob Media Player Control"
  description: >
    **Version 1.2.0** - Fixed rotation responsiveness with queued commands


    Control a media player with a MOES Smart Knob (ERS-10TZBVK-AA) via Zigbee2MQTT.


    **The knob must be in EVENT mode** (triple-click to switch modes).


    - **Single press**: Run a configurable action (e.g., home cinema ON script)

    - **Double press**: Run a configurable action (e.g., home cinema OFF script)

    - **Rotate right**: Volume up (one step per tick)

    - **Rotate left**: Volume down (one step per tick)

    - **Hold (3s)**: Mute toggle


    Volume control uses the media player's native step size for immediate response.
    Each knob tick sends one volume command. Commands are queued so rapid rotations
    are never lost.
  domain: automation
  author: "Jan Singer"
  homeassistant:
    min_version: "2024.6.0"
  input:
    mqtt_settings:
      name: "MQTT Configuration"
      icon: mdi:antenna
      collapsed: false
      description: "Zigbee2MQTT connection settings for the MOES Smart Knob."
      input:
        base_topic:
          name: "Zigbee2MQTT Base Topic"
          description: >
            The base MQTT topic configured in your Zigbee2MQTT settings.
            Default is `zigbee2mqtt` unless you changed it.
          default: "zigbee2mqtt"
          selector:
            text: {}
        mqtt_device_name:
          name: "MQTT Device Friendly Name"
          description: >
            The friendly name of your MOES Smart Knob as configured in
            Zigbee2MQTT (e.g., `moes_knob_living_room`). This is used to
            construct the MQTT topic: `<base_topic>/<friendly_name>/action`.
          selector:
            text: {}
    media_player_settings:
      name: "Media Player"
      icon: mdi:speaker
      collapsed: false
      description: "Media player entity to control."
      input:
        media_player:
          name: "Media Player Entity"
          description: >
            The media player to control with the knob rotation.
            Volume step size is determined by the device's native increment.
          selector:
            entity:
              filter:
                - domain: media_player
    button_actions:
      name: "Button Actions"
      icon: mdi:gesture-tap
      collapsed: false
      description: "Actions to run on single press, double press, and hold."
      input:
        single_press_action:
          name: "Single Press Action"
          description: >
            Action to run on a single press (e.g., run a home cinema ON script).
          default: []
          selector:
            action: {}
        double_press_action:
          name: "Double Press Action"
          description: >
            Action to run on a double press (e.g., run a home cinema OFF script).
          default: []
          selector:
            action: {}

mode: queued
max: 20
max_exceeded: silent

trigger_variables:
  base_topic: !input base_topic
  mqtt_device_name: !input mqtt_device_name

trigger:
  - trigger: mqtt
    topic: "{{ base_topic ~ '/' ~ mqtt_device_name ~ '/action' }}"

action:
  - variables:
      payload: "{{ trigger.payload }}"
      media_player_id: !input media_player
      is_player_on: >-
        {{ states(media_player_id) not in ['off', 'unavailable', 'unknown'] }}
  - choose:
      # --- Single Press: Home Cinema ON ---
      - conditions:
          - "{{ payload == 'single' }}"
        sequence: !input single_press_action

      # --- Double Press: Home Cinema OFF ---
      - conditions:
          - "{{ payload == 'double' }}"
        sequence: !input double_press_action

      # --- Rotate Right: Volume Up ---
      - conditions:
          - "{{ payload == 'rotate_right' }}"
          - "{{ is_player_on }}"
        sequence:
          - action: media_player.volume_up
            target:
              entity_id: !input media_player

      # --- Rotate Left: Volume Down ---
      - conditions:
          - "{{ payload == 'rotate_left' }}"
          - "{{ is_player_on }}"
        sequence:
          - action: media_player.volume_down
            target:
              entity_id: !input media_player

      # --- Hold: Mute Toggle ---
      - conditions:
          - "{{ payload == 'hold' }}"
          - "{{ is_player_on }}"
        sequence:
          - action: media_player.volume_mute
            target:
              entity_id: !input media_player
            data:
              is_volume_muted: >-
                {{ not state_attr(media_player_id, 'is_volume_muted') }}
