blueprint:
  name: "Zigbee2MQTT - MOES Smart Knob Media Player Control (Legacy)"
  description: >
    **Version 3.0.0** - SUPERSEDED by v4.0.0 two-automation approach


    ⚠️ **This blueprint has been replaced by:**

    - `blueprint-z2m-knob-accumulator.yaml` (Part 1)

    - `blueprint-z2m-volume-applier.yaml` (Part 2)


    The two-automation approach fixes the issue where rapid rotations are dropped
    because `mode: single` + `max_exceeded: silent` silently discards events that
    arrive before `wait_for_trigger` starts.


    ---


    Control a media player with a MOES Smart Knob (ERS-10TZBVK-AA) via Zigbee2MQTT.


    **Requires two helpers:**

    1. **Counter** (Settings → Helpers → Counter): min: -100, max: 100, initial: 0

    2. **Input Number** (Settings → Helpers → Number): min: 0, max: 1, step: 0.01


    **The knob must be in EVENT mode** (triple-click to switch modes).


    - **Rotate right/left**: Volume up/down (all rotations accumulated atomically)

    - **Single press**: Run configurable action (e.g., home cinema ON)

    - **Double press**: Run configurable action (e.g., home cinema OFF)

    - **Hold (3s)**: Sync volume helper from device (use if out of sync)


    Rotations are collected in a 150ms window using atomic counter operations,
    then a single volume command is sent.
  domain: automation
  author: "Jan Singer"
  homeassistant:
    min_version: "2024.6.0"
  input:
    mqtt_settings:
      name: "MQTT Configuration"
      icon: mdi:antenna
      collapsed: false
      description: "Zigbee2MQTT connection settings for the MOES Smart Knob."
      input:
        base_topic:
          name: "Zigbee2MQTT Base Topic"
          description: >
            The base MQTT topic configured in your Zigbee2MQTT settings.
            Default is `zigbee2mqtt` unless you changed it.
          default: "zigbee2mqtt"
          selector:
            text: {}
        mqtt_device_name:
          name: "MQTT Device Friendly Name"
          description: >
            The friendly name of your MOES Smart Knob as configured in
            Zigbee2MQTT (e.g., `moes_knob_living_room`). This is used to
            construct the MQTT topic: `<base_topic>/<friendly_name>/action`.
          selector:
            text: {}
    media_player_settings:
      name: "Media Player & Volume"
      icon: mdi:speaker
      collapsed: false
      description: "Media player entity and volume tracking helpers."
      input:
        media_player:
          name: "Media Player Entity"
          description: >
            The media player to control (e.g., Arcam AV40).
          selector:
            entity:
              filter:
                - domain: media_player
        volume_helper:
          name: "Volume Tracking Helper"
          description: >
            An input_number helper to track target volume. Create one at
            Settings → Helpers → Number with min: 0, max: 1, step: 0.01.
          selector:
            entity:
              filter:
                - domain: input_number
        rotation_counter:
          name: "Rotation Counter"
          description: >
            A counter helper to accumulate rotations atomically. Create one at
            Settings → Helpers → Counter with min: -100, max: 100, initial: 0.
          selector:
            entity:
              filter:
                - domain: counter
        volume_step:
          name: "Volume Step (%)"
          description: >
            Volume percentage change per rotation tick. 2% recommended.
          default: 2
          selector:
            number:
              min: 1
              max: 10
              step: 1
              unit_of_measurement: "%"
              mode: slider
    button_actions:
      name: "Button Actions"
      icon: mdi:gesture-tap
      collapsed: false
      description: "Actions to run on single press and double press."
      input:
        single_press_action:
          name: "Single Press Action"
          description: >
            Action to run on a single press (e.g., run a home cinema ON script).
          default: []
          selector:
            action: {}
        double_press_action:
          name: "Double Press Action"
          description: >
            Action to run on a double press (e.g., run a home cinema OFF script).
          default: []
          selector:
            action: {}

mode: single
max_exceeded: silent

trigger_variables:
  base_topic: !input base_topic
  mqtt_device_name: !input mqtt_device_name

trigger:
  - trigger: mqtt
    topic: "{{ base_topic ~ '/' ~ mqtt_device_name ~ '/action' }}"

action:
  - variables:
      payload: "{{ trigger.payload }}"
      media_player_id: !input media_player
      volume_helper_id: !input volume_helper
      rotation_counter_id: !input rotation_counter
      volume_step: !input volume_step
      mqtt_topic: "{{ base_topic ~ '/' ~ mqtt_device_name ~ '/action' }}"
      is_player_on: >-
        {{ states(media_player_id) not in ['off', 'unavailable', 'unknown'] }}

  - choose:
      # --- Single Press ---
      - conditions:
          - "{{ payload == 'single' }}"
        sequence: !input single_press_action

      # --- Double Press ---
      - conditions:
          - "{{ payload == 'double' }}"
        sequence: !input double_press_action

      # --- Rotation: Accumulate with counter and apply ---
      - conditions:
          - "{{ payload in ['rotate_right', 'rotate_left'] }}"
          - "{{ is_player_on }}"
        sequence:
          # Step 1: Record this rotation using atomic counter operation
          - action: "counter.{{ 'increment' if payload == 'rotate_right' else 'decrement' }}"
            target:
              entity_id: !input rotation_counter

          # Step 2: Collect more rotations in 150ms window
          - repeat:
              sequence:
                - wait_for_trigger:
                    - trigger: mqtt
                      topic: "{{ mqtt_topic }}"
                  timeout:
                    milliseconds: 150
                  continue_on_timeout: true

                - choose:
                    - conditions:
                        - "{{ wait.trigger is not none and wait.trigger.payload == 'rotate_right' }}"
                      sequence:
                        - action: counter.increment
                          target:
                            entity_id: !input rotation_counter
                    - conditions:
                        - "{{ wait.trigger is not none and wait.trigger.payload == 'rotate_left' }}"
                      sequence:
                        - action: counter.decrement
                          target:
                            entity_id: !input rotation_counter

              until:
                - "{{ wait.trigger is none or wait.trigger.payload not in ['rotate_right', 'rotate_left'] }}"

          # Step 3: Read counter and calculate new volume
          - variables:
              rotation_count: "{{ states(rotation_counter_id) | int(0) }}"
              current_vol: "{{ states(volume_helper_id) | float(0.5) }}"
              new_vol: "{{ [[current_vol + (rotation_count * volume_step / 100), 0.0] | max, 1.0] | min }}"

          # Step 4: Reset counter for next rotation sequence
          - action: counter.reset
            target:
              entity_id: !input rotation_counter

          # Step 5: Update shadow volume helper
          - action: input_number.set_value
            target:
              entity_id: !input volume_helper
            data:
              value: "{{ new_vol }}"

          # Step 6: Send final volume to device
          - action: media_player.volume_set
            target:
              entity_id: !input media_player
            data:
              volume_level: "{{ new_vol }}"

          # Step 7: Handle any button press that was caught during rotation
          - choose:
              - conditions:
                  - "{{ wait.trigger is not none and wait.trigger.payload == 'single' }}"
                sequence: !input single_press_action
              - conditions:
                  - "{{ wait.trigger is not none and wait.trigger.payload == 'double' }}"
                sequence: !input double_press_action
              - conditions:
                  - "{{ wait.trigger is not none and wait.trigger.payload == 'hold' }}"
                sequence:
                  - action: input_number.set_value
                    target:
                      entity_id: !input volume_helper
                    data:
                      value: "{{ state_attr(media_player_id, 'volume_level') | float(0.5) }}"

      # --- Hold: Sync helper from device ---
      - conditions:
          - "{{ payload == 'hold' }}"
          - "{{ is_player_on }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: !input volume_helper
            data:
              value: "{{ state_attr(media_player_id, 'volume_level') | float(0.5) }}"
